import 'package:flutter/material.dart';
import '../models/grievance.dart';
import '../models/department.dart';
import '../models/chat_message.dart';

class MockDataService {
  static List<Grievance> getInitialGrievances() {
    final now = DateTime.now();

    return [
      Grievance(
        id: 'JM-2026-8891',
        title: 'Major Underground Pipe Burst & Contaminated Supply',
        description: 'Potable water supply has turned muddy with sewage odor since yesterday morning. Over 300 households affected.',
        category: GrievanceCategory.waterSupply,
        priority: GrievancePriority.urgent,
        status: GrievanceStatus.escalated,
        urgencyScore: 94,
        location: 'Sector 4, Main Pipeline Junction, Ward 12',
        ward: 'Ward 12 (Central Zone)',
        duplicateCount: 14,
        filedAt: now.subtract(const Duration(hours: 18)),
        assignedOfficer: 'Er. Rajesh V. (Executive Engineer - Water Works)',
        aiActionRecommendation: 'Dispatch Emergency Pipeline Repair Squad + Mobilize 4 Clean Water Tankers to Sector 4 within 2 Hours.',
        sentiment: 'Extreme Public Concern & Health Risk',
        similarityAlert: 'High similarity (94%) detected across 14 complaints in 500m radius.',
        upvotes: 87,
        timeline: [
          TimelineStep(
            title: 'Grievance Registered',
            timestamp: 'Yesterday 14:30',
            description: 'Submitted via JanMitra Citizen Portal with 3 photos.',
            isCompleted: true,
            actor: 'Citizen (Anita Sharma)',
          ),
          TimelineStep(
            title: 'AI Triage & Clustering',
            timestamp: 'Yesterday 14:32',
            description: 'AI System grouped 14 duplicate reports into Master Alert JM-2026-8891. Urgency score set to 94%.',
            isCompleted: true,
            actor: 'JanMitra AI Core Engine',
          ),
          TimelineStep(
            title: 'Assigned to Officer',
            timestamp: 'Yesterday 15:10',
            description: 'Automated notification sent to EE Water Works.',
            isCompleted: true,
            actor: 'Auto Dispatcher',
          ),
          TimelineStep(
            title: 'SLA Limit Exceeded Alert',
            timestamp: 'Today 06:30',
            description: '12-hour SLA window exceeded. Escalated to District Collector Dashboard.',
            isCompleted: true,
            actor: 'JanMitra Governance Sentinel',
          ),
          TimelineStep(
            title: 'Field Team Dispatch & Containment',
            timestamp: 'Expected Today 10:00',
            description: 'Repair crew on site isolating contaminated sub-line.',
            isCompleted: false,
            actor: 'Field Crew Alpha',
          ),
        ],
      ),
      Grievance(
        id: 'JM-2026-8742',
        title: 'Dangerous Potholes on MG Road Flyover Ramp',
        description: 'Large 2-foot deep potholes causing extreme braking and 2 motorcycle skidding accidents in rainy weather.',
        category: GrievanceCategory.roadsAndInfrastructure,
        priority: GrievancePriority.high,
        status: GrievanceStatus.inProgress,
        urgencyScore: 82,
        location: 'MG Road Flyover North Exit, Ward 7',
        ward: 'Ward 7 (North Zone)',
        duplicateCount: 8,
        filedAt: now.subtract(const Duration(hours: 36)),
        assignedOfficer: 'Shri R. K. Gupta (Sub-Divisional Engineer - PWD)',
        aiActionRecommendation: 'Apply Cold-Mix Asphalt Patching immediately. Set up safety barricades.',
        sentiment: 'High Traffic Safety Risk',
        similarityAlert: '8 similar complaints logged near Flyover North Exit.',
        upvotes: 45,
        timeline: [
          TimelineStep(
            title: 'Grievance Registered',
            timestamp: '2 Days Ago 09:15',
            description: 'Registered with GPS tagging.',
            isCompleted: true,
            actor: 'Citizen (Rahul Verma)',
          ),
          TimelineStep(
            title: 'AI Priority Assessment',
            timestamp: '2 Days Ago 09:16',
            description: 'Categorized as High Priority Road Safety Risk.',
            isCompleted: true,
            actor: 'JanMitra AI Core',
          ),
          TimelineStep(
            title: 'Inspection & Crew Deployment',
            timestamp: 'Yesterday 11:00',
            description: 'PWD Inspector verified damage. Cold-mix patching vehicle scheduled.',
            isCompleted: true,
            actor: 'SDE PWD',
          ),
          TimelineStep(
            title: 'Final Quality Check & Resolution',
            timestamp: 'In Progress',
            description: 'Patching work 70% completed.',
            isCompleted: false,
            actor: 'PWD Field Team',
          ),
        ],
      ),
      Grievance(
        id: 'JM-2026-8610',
        title: 'High Voltage Surge & Transformer Sparking',
        description: 'Frequent voltage spikes burning household appliances. Sparks observed on pole transformer #T-42.',
        category: GrievanceCategory.electricity,
        priority: GrievancePriority.high,
        status: GrievanceStatus.inProgress,
        urgencyScore: 78,
        location: 'Green Park Extension, Ward 15',
        ward: 'Ward 15 (East Zone)',
        duplicateCount: 5,
        filedAt: now.subtract(const Duration(hours: 12)),
        assignedOfficer: 'Er. S. Nair (Assistant Engineer - Electricity Board)',
        aiActionRecommendation: 'De-energize transformer #T-42 loop, replace burnt load balancer fuse, recalibrate phase voltage.',
        sentiment: 'Concern & Fire Hazard Alert',
        upvotes: 31,
        timeline: [
          TimelineStep(
            title: 'Grievance Registered',
            timestamp: 'Today 01:20',
            description: 'Reported during night outage.',
            isCompleted: true,
            actor: 'Resident Welfare Assoc.',
          ),
          TimelineStep(
            title: 'AI Fire Risk Classification',
            timestamp: 'Today 01:21',
            description: 'Flagged as High Urgency Electrical Hazard.',
            isCompleted: true,
            actor: 'JanMitra AI Core',
          ),
          TimelineStep(
            title: 'Lineman Dispatched',
            timestamp: 'Today 07:00',
            description: 'Lineman team inspecting Transformer #T-42.',
            isCompleted: true,
            actor: 'AE Electricity Board',
          ),
        ],
      ),
      Grievance(
        id: 'JM-2026-8501',
        title: 'Uncollected Municipal Solid Waste & Stray Cattle',
        description: 'Waste collection truck missed street for 4 days. Overflowing bins attracting stray dogs and cattle, blocking road.',
        category: GrievanceCategory.sanitation,
        priority: GrievancePriority.medium,
        status: GrievanceStatus.underReview,
        urgencyScore: 61,
        location: 'Market Yard Lane 3, Ward 3',
        ward: 'Ward 3 (South Zone)',
        duplicateCount: 3,
        filedAt: now.subtract(const Duration(hours: 8)),
        assignedOfficer: 'Dr. Meena Swaminathan (Chief Sanitation Officer)',
        aiActionRecommendation: 'Reroute Compact-Garbage Vehicle #14 to Lane 3. Spray disinfectant post-clearance.',
        sentiment: 'Public Hygiene Discontent',
        upvotes: 19,
        timeline: [
          TimelineStep(
            title: 'Grievance Registered',
            timestamp: 'Today 07:30',
            description: 'Logged with photo proof of bin overflowing.',
            isCompleted: true,
            actor: 'Citizen (Vikas Sethi)',
          ),
          TimelineStep(
            title: 'AI Smart Route Optimization',
            timestamp: 'Today 07:32',
            description: 'Suggested route adjustment for Sanitation Vehicle #14.',
            isCompleted: true,
            actor: 'JanMitra AI Core',
          ),
        ],
      ),
      Grievance(
        id: 'JM-2026-8400',
        title: 'Dark Corridor: 12 Consecutive Streetlights Defective',
        description: 'Entire 800m stretch of Ring Road bypass lights are non-functional. Poses safety risks for evening commuters.',
        category: GrievanceCategory.streetlights,
        priority: GrievancePriority.medium,
        status: GrievanceStatus.submitted,
        urgencyScore: 54,
        location: 'Ring Road Service Bypass, Ward 19',
        ward: 'Ward 19 (West Zone)',
        duplicateCount: 2,
        filedAt: now.subtract(const Duration(hours: 4)),
        assignedOfficer: 'Pending Automated Assignment',
        aiActionRecommendation: 'Inspect feeder pillar #FP-19 for trip switch failure. Replace LED drivers if required.',
        sentiment: 'Safety & Visibility Concern',
        upvotes: 14,
        timeline: [
          TimelineStep(
            title: 'Grievance Registered',
            timestamp: 'Today 11:00',
            description: 'Submitted with GPS coordinates.',
            isCompleted: true,
            actor: 'Citizen (Pooja Rao)',
          ),
        ],
      ),
      Grievance(
        id: 'JM-2026-8110',
        title: 'Stagnant Stormwater Drain Overflow near Primary School',
        description: 'Clogged storm drain overflowing near Govt Primary School. Health hazard for children during monsoon rains.',
        category: GrievanceCategory.publicHealth,
        priority: GrievancePriority.urgent,
        status: GrievanceStatus.resolved,
        urgencyScore: 89,
        filedAt: now.subtract(const Duration(days: 3)),
        resolvedAt: now.subtract(const Duration(hours: 14)),
        location: 'Govt Primary School Road, Ward 12',
        ward: 'Ward 12 (Central Zone)',
        duplicateCount: 9,
        assignedOfficer: 'Er. Rajesh V. (Executive Engineer - Water Works)',
        aiActionRecommendation: 'Deploy High-Pressure Suction Jetting machine to clear silt blockages.',
        sentiment: 'Resolved - High Public Relief',
        upvotes: 62,
        timeline: [
          TimelineStep(
            title: 'Grievance Filed',
            timestamp: '3 Days Ago',
            description: 'Reported by School Principal.',
            isCompleted: true,
          ),
          TimelineStep(
            title: 'AI Priority Dispatch',
            timestamp: '3 Days Ago',
            description: 'Flagged P1 Urgent due to proximity to school children.',
            isCompleted: true,
          ),
          TimelineStep(
            title: 'Suction Clearance Completed',
            timestamp: 'Yesterday 18:00',
            description: 'Silt removed, drain cleared, anti-mosquito larvicide sprayed.',
            isCompleted: true,
            actor: 'Health & Municipal Sanitation Team',
          ),
          TimelineStep(
            title: 'Citizen Verification',
            timestamp: 'Yesterday 18:30',
            description: 'School Principal confirmed 100% resolution.',
            isCompleted: true,
          ),
        ],
      ),
    ];
  }

  static List<DepartmentMetric> getDepartmentMetrics() {
    return [
      DepartmentMetric(
        name: 'Water Supply & Sewage',
        icon: Icons.water_drop_rounded,
        totalComplaints: 342,
        resolvedComplaints: 310,
        pendingComplaints: 32,
        slaCompliancePercent: 90.6,
        avgResolutionHours: 14.2,
        satisfactionScore: 4.5,
        weeklyTrend: [42, 55, 38, 60, 48, 51, 48],
      ),
      DepartmentMetric(
        name: 'Roads & Infrastructure (PWD)',
        icon: Icons.add_road_rounded,
        totalComplaints: 520,
        resolvedComplaints: 462,
        pendingComplaints: 58,
        slaCompliancePercent: 88.8,
        avgResolutionHours: 28.5,
        satisfactionScore: 4.2,
        weeklyTrend: [80, 95, 72, 65, 78, 68, 62],
      ),
      DepartmentMetric(
        name: 'Electricity Board',
        icon: Icons.electric_bolt_rounded,
        totalComplaints: 289,
        resolvedComplaints: 278,
        pendingComplaints: 11,
        slaCompliancePercent: 96.2,
        avgResolutionHours: 6.4,
        satisfactionScore: 4.8,
        weeklyTrend: [35, 40, 28, 45, 52, 49, 40],
      ),
      DepartmentMetric(
        name: 'Sanitation & Solid Waste',
        icon: Icons.cleaning_services_rounded,
        totalComplaints: 415,
        resolvedComplaints: 390,
        pendingComplaints: 25,
        slaCompliancePercent: 93.9,
        avgResolutionHours: 11.0,
        satisfactionScore: 4.6,
        weeklyTrend: [50, 62, 58, 60, 55, 68, 62],
      ),
      DepartmentMetric(
        name: 'Public Health & Hygiene',
        icon: Icons.health_and_safety_rounded,
        totalComplaints: 180,
        resolvedComplaints: 168,
        pendingComplaints: 12,
        slaCompliancePercent: 93.3,
        avgResolutionHours: 12.8,
        satisfactionScore: 4.7,
        weeklyTrend: [22, 30, 25, 28, 24, 26, 25],
      ),
    ];
  }

  static List<ChatMessage> getInitialChatMessages() {
    return [
      ChatMessage(
        id: 'msg-1',
        text: 'Namaste! I am JanMitra AI, your Public Grievance Assistant. How can I support you today?',
        isUser: false,
        timestamp: DateTime.now().subtract(const Duration(minutes: 5)),
        suggestedActions: [
          'File a new grievance',
          'Check status of JM-2026-8891',
          'Report water leakage',
          'View ward heatmaps',
        ],
      ),
    ];
  }
}
