"""add extraction fields to attachments

Revision ID: 937ffb8a201e
Revises: f694f8b328d1
Create Date: 2026-08-14 22:43:19.823263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '937ffb8a201e'
down_revision: Union[str, None] = 'f694f8b328d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grievance_attachments', sa.Column('extraction_status', sa.String(length=50), server_default='pending', nullable=False))
    op.add_column('grievance_attachments', sa.Column('extraction_confidence', sa.Float(), nullable=True))
    op.add_column('grievance_attachments', sa.Column('extraction_engine', sa.String(length=100), nullable=True))
    op.add_column('grievance_attachments', sa.Column('extraction_error', sa.Text(), nullable=True))
    op.add_column('grievance_attachments', sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grievance_attachments', 'extracted_at')
    op.drop_column('grievance_attachments', 'extraction_error')
    op.drop_column('grievance_attachments', 'extraction_engine')
    op.drop_column('grievance_attachments', 'extraction_confidence')
    op.drop_column('grievance_attachments', 'extraction_status')
    # ### end Alembic commands ###
