"""create grievance foundation tables

Revision ID: f694f8b328d1
Revises: b99ce809cb3a
Create Date: 2026-08-11 01:33:15.369808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f694f8b328d1'
down_revision: Union[str, None] = 'b99ce809cb3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grievances',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('grievance_number', sa.String(length=50), nullable=False),
    sa.Column('citizen_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('intake_mode', sa.String(length=50), nullable=False),
    sa.Column('original_language', sa.String(length=20), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('translated_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('confirmed_location', sa.JSON(), nullable=True),
    sa.Column('location_sources', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['citizen_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grievances_citizen_id'), 'grievances', ['citizen_id'], unique=False)
    op.create_index(op.f('ix_grievances_grievance_number'), 'grievances', ['grievance_number'], unique=True)
    op.create_index(op.f('ix_grievances_id'), 'grievances', ['id'], unique=False)
    op.create_table('grievance_attachments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('grievance_id', sa.String(length=36), nullable=False),
    sa.Column('attachment_type', sa.String(length=50), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('raw_extracted_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['grievance_id'], ['grievances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grievance_attachments_grievance_id'), 'grievance_attachments', ['grievance_id'], unique=False)
    op.create_index(op.f('ix_grievance_attachments_id'), 'grievance_attachments', ['id'], unique=False)
    op.create_table('grievance_audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('grievance_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('actor_role', sa.String(length=50), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('previous_state', sa.String(length=50), nullable=True),
    sa.Column('new_state', sa.String(length=50), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['grievance_id'], ['grievances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grievance_audit_logs_grievance_id'), 'grievance_audit_logs', ['grievance_id'], unique=False)
    op.create_index(op.f('ix_grievance_audit_logs_id'), 'grievance_audit_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grievance_audit_logs_id'), table_name='grievance_audit_logs')
    op.drop_index(op.f('ix_grievance_audit_logs_grievance_id'), table_name='grievance_audit_logs')
    op.drop_table('grievance_audit_logs')
    op.drop_index(op.f('ix_grievance_attachments_id'), table_name='grievance_attachments')
    op.drop_index(op.f('ix_grievance_attachments_grievance_id'), table_name='grievance_attachments')
    op.drop_table('grievance_attachments')
    op.drop_index(op.f('ix_grievances_id'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_grievance_number'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_citizen_id'), table_name='grievances')
    op.drop_table('grievances')
    # ### end Alembic commands ###
